---
title: "Reproducible Research: Peer Assessment 1"
Author: S.Sujit
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data from csv file format
```{r, echo = TRUE}
library(ggplot2)

data <- read.table('activity.csv',sep = ",",header = TRUE, na.strings ="NA",colClasses = c('integer','Date','factor'))

# missing value has been treated and stored as a new dataframe
new.data <- na.omit(data)
```



## What is mean total number of steps taken per day?

```{r, echo=TRUE}
# Calculated the total number of steps taken per day
total.steps <- tapply(new.data$steps, new.data$date, FUN = sum)

# making a histogram 
p1 <- ggplot(new.data, aes(date, steps)) + geom_bar(stat = "identity",binwidth = .5, col = "red") + labs(title = "Steps Taken Each Day",x = "Name of Months", y = "Number of Steps")
print(p1)

# calculated mean and median value by following Number of steps per day
mean(total.steps)
median(total.steps)
```


## What is the average daily activity pattern?
```{r, echo=TRUE}

averages <- aggregate(new.data$steps, list(interval = as.numeric(as.character(new.data$interval))), FUN = "mean")
names(averages)[2] <- "Avg.Steps"

p2 <- ggplot(averages, aes(interval, Avg.Steps)) + geom_line(color = "red", size = 0.9) + labs(title = "Trend of Setps Taken and Time Intervals", x = "5-minute intervals", y = "Average Number of Steps Taken")
print(p2)
```



## Imputing missing values

```{r, echo=TRUE}
averages[averages$Avg.Steps == max(averages$Avg.Steps),]
sum(!complete.cases(data))
```


```{r, echo=TRUE}
impData <- data 
for (i in 1:nrow(impData)) {
    if (is.na(impData$steps[i])) {
        impData$steps[i] <- averages[which(impData$interval[i]
        == averages$interval), ]$Avg.Steps
    }
}
```


```{r, echo=TRUE}
sum(!complete.cases(impData))
p3 <- ggplot(impData, aes(date, steps)) + geom_bar(stat = "identity",binwidth = .5, col = "red") + labs(title = "Daily Steps Taken Each Day (Imputed Data)",x = "Name of Month", y = "Total Number of Steps")
print(p3)
```



```{r, echo=TRUE}
total.steps.impute <- tapply(impData$steps, impData$date, FUN = sum)
mean(total.steps.impute)
median(total.steps.impute)
```



## Are there differences in activity patterns between weekdays and weekends?
```{r, echo=TRUE}
impData$weekdays <- factor(format(impData$date, "%A"))
levels(impData$weekdays)
levels(impData$weekdays) <- list(weekday = c("Monday", "Tuesday","Wednesday", "Thursday", "Friday"), weekend = c("Saturday", "Sunday"))
levels(impData$weekdays)
table(impData$weekdays)


new.averages <- aggregate(impData$steps,list(interval = as.numeric(as.character(impData$interval)), weekdays = impData$weekdays), FUN = "mean")
names(new.averages)[3] <- "meanOfSteps"

# loading lattice package and making plot

library(lattice)
p4 <- xyplot(new.averages$meanOfSteps ~ new.averages$interval | new.averages$weekdays, layout = c(1, 2), type = "l", xlab = "Interval", ylab = "Number of steps")
print(p4)
```

